jumphost: "{{ ansible_fqdn }}"
beaker_server_name: beaker_server
beaker_lab_name: beaker_lab_controller
beaker_pod_name: beaker
data_dir: /opt
ports:
  - 80
  - 8000
beaker_server_image: quay.io/p3ck/beaker-server:latest
beaker_lab_image: quay.io/p3ck/beaker-lab-controller:latest
beaker_mysql_image: registry.redhat.io/rhel8/mariadb-103
mysql_database: beaker
mysql_user: beaker
mysql_password: beaker
mysql_root_password: password
mysql_charset: utf8
file_owner: "{{ ansible_env.USER }}"
file_group: "{{ file_owner }}"
config_file_path: /tmp/wip/config
dns_servers: []
beaker_extra_config: {}
